name: CI

on:
  push:
    paths:
      - "cmd/tb/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cmd/tb
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: cmd/tb/go.mod
      - name: gofmt
        run: |
          files=$(gofmt -l .)
          if [ -n "$files" ]; then
            echo "$files"
            exit 1
          fi
      - name: go vet
        run: go vet ./...
      - name: go test
        run: go test ./...
